### ISSUE TITLE
Explain how to chain the importing and rendering steps

### ISSUE THREAD

**Issue by sbesson** [ome/omero-guide-upload#10]
See https://forum.image.sc/t/automated-import/42740/15

As mentioned in the forum thread, when uploading/annotating/rendering data, it is possible to chain CLI commands by using the object identifiers which are generated as the standard output of import. It should be possible to construct either an amendment of the current  workflow or an alternate workflow that demonstrates how to create such a pipeline.

**Comment by pwalczysko** [comment]
suggested fix in https://github.com/ome/omero-guide-upload/pull/11

**Comment by sbesson** [comment]
:+1: do you want to annotate the associated Pull Request with a [GitHub keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so that the issue is auto-close on merge?
