### ISSUE TITLE
Link to the readthedocs website for this guide

### ISSUE THREAD

**Issue by manics** [ome/omero-guide-upload#7]
If someone finds this repository it should be easy for them to find the deployed guide on readthedocs. This is also useful for anyone reviewing PRs who wants to view the existing content. Currently it's blank:

![image](https://user-images.githubusercontent.com/1644105/83732986-cb7a5380-a644-11ea-9fa4-4835d5abeef3.png)

**Comment by pwalczysko** [comment]
Solved, see https://github.com/ome/omero-guide-upload

Closing
